services:
  - type: web
    name: atiun-server
    runtime: image
    dockerCommand: atuin server start
    autoDeploy: false
    image:
      url: ghcr.io/ellie/atuin:latest
    envVars:
      - key: ATUIN_HOST
        value: 0.0.0.0
      - key: ATUIN_OPEN_REGISTRATION
        value: false # change to true to allow registrations
      - key: ATUIN_DB_URI
        fromDatabase:
          name: atuin-db
          property: connectionString

databases:
  - name: atuin-db
    databaseName: private
    ipAllowList: []